import type { Metadata } from "next";

import { api } from "@/convex/_generated/api";
import { convexAuthNextjsToken } from "@convex-dev/auth/nextjs/server";
import { fetchQuery } from "convex/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function ShareLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const token = await convexAuthNextjsToken();
  const currentUser = token
    ? await fetchQuery(api.users.getUser, {}, { token })
    : null;

  return <div className="w-full">{children}</div>;
}
